### ISSUE TITLE
Error on import

### ISSUE THREAD

**Issue by berzi** [voidism/pywordseg#5]
Hi. I'm trying to instantiate Wordseg for the first time, using default arguments:
```python
import pywordseg

...

segmenter = pywordseg.Wordseg()
```

But after everything is downloaded, I get an error on the import statement (which presents itself if I retry too, minus the downloading):
```
Using pywordseg for the first time, download CharEmb model.
Download models ...100%, 29 MB, 8395 KB/s, 3 seconds passed
CharEmb built!
Using pywordseg for the first time, download main segmentation system models.
Download models ...100%, 212 MB, 8245 KB/s, 26 seconds passed
models built!
Using pywordseg for the first time, download ELMo model.
Download models ...100%, 336 MB, 8846 KB/s, 39 seconds passed
ELMoForManyLangs built!
Traceback (most recent call last):
  File "E:\Programming\stuff\main.py", line 4, in <module>
    import pywordseg
  File "E:\Programming\stuff\venv\lib\site-packages\pywordseg\__init__.py", line 20, in <module>
    from .pywordseg import Wordseg
  File "E:\Programming\stuff\venv\lib\site-packages\pywordseg\pywordseg.py", line 5, in <module>
    from .ELMoForManyLangs import elmo
  File "E:\Programming\stuff\venv\lib\site-packages\pywordseg\ELMoForManyLangs\elmo.py", line 22, in <module>
    from .src.modules.token_embedder import ConvTokenEmbedder, LstmTokenEmbedder
  File "E:\Programming\stuff\venv\lib\site-packages\pywordseg\ELMoForManyLangs\src\modules\token_embedder.py", line 9, in <module>
    from .highway import Highway
  File "E:\Programming\stuff\venv\lib\site-packages\pywordseg\ELMoForManyLangs\src\modules\highway.py", line 12, in <module>
    class Highway(torch.nn.Module):
  File "E:\Programming\stuff\venv\lib\site-packages\pywordseg\ELMoForManyLangs\src\modules\highway.py", line 47, in Highway
    def forward(self, inputs: torch.Tensor) -> torch.Tensor:  # pylint: disable=arguments-differ
  File "E:\Programming\stuff\venv\lib\site-packages\overrides\overrides.py", line 88, in overrides
    return _overrides(method, check_signature, check_at_runtime)
  File "E:\Programming\stuff\venv\lib\site-packages\overrides\overrides.py", line 114, in _overrides
    _validate_method(method, super_class, check_signature)
  File "E:\Programming\stuff\venv\lib\site-packages\overrides\overrides.py", line 135, in _validate_method
    ensure_signature_is_compatible(super_method, method, is_static)
  File "E:\Programming\stuff\venv\lib\site-packages\overrides\signature.py", line 93, in ensure_signature_is_compatible
    ensure_return_type_compatibility(super_type_hints, sub_type_hints, method_name)
  File "E:\Programming\stuff\venv\lib\site-packages\overrides\signature.py", line 287, in ensure_return_type_compatibility
    raise TypeError(
TypeError: Highway.forward: return type `<class 'torch.Tensor'>` is not a `<class 'NoneType'>`.
```

I'm running this on Python 3.9.

What's going on, how can I fix this?

**Comment by voidism** [comment]
Hi @berzi 

I found that this problem is caused by the `overrides` package. I just downgrade to `overrides==1.9` and it works fine for me!

**Comment by berzi** [comment]
That fixed it, thank you so much!
